### ISSUE TITLE
server misbehaving

### ISSUE THREAD

**Issue by lapin7** [synereo/dockernode#2]
Sorry, but I got a new error. Hopefully you can do something about it :-)

bash-3.2$ docker pull synereo/synereo
Pulling repository synereo/synereo
FATA[0015] Get https://index.docker.io/v1/repositories/synereo/synereo/images: dial tcp: lookup index.docker.io on 212.159.225.196:53: server misbehaving 

Cheers HJ

**Comment by yuvadm** [comment]
Looks like a docker hub error. Can you test this on another machine or network?

**Comment by lapin7** [comment]
Sorry, it's my fault. I've restarted boot2docker. And download runs fine.

**Comment by lapin7** [comment]
But where does the download go? Into which directory?

**Comment by yuvadm** [comment]
The physical location doesn't matter (it's probably `/var/lib/docker/` something, depending on your distro. not sure how b2d does it). The image should show up if you type:

``` bash
$ docker images
```

I suggest you get acquainted with Docker and read some of the basic docs before continuing, it'll make the process easier :)

**Comment by lapin7** [comment]
Yep the image shows up and I will read the Docker documentation more carefully. Thanks for your help.
