### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by CMsynereo** [synereo/dockernode#4]
For dummies like me it took a while to understand the text below.
Please change the following text.

**after that jump to 'Running' section below and change the docker image to livelygig/backend from spliciousbkendimage in docker run command.**

Into

after that jump to 'Running' section below.
And change the image in the docker run command:
- replace IP_ADDRESS with: 192.168.99.100
- replace spliciousbkendimage with: livelygig/backend

3a. docker run -it -e MONGODB_HOST=IP_ADDRESS -e MONGODB_PORT=27017 \
               --name backendNode -p 8888:9876 -d spliciousbkendimage /usr/local/splicious/run.sh

so that it becomes:

**3a. docker run -it -e MONGODB_HOST=192.168.99.100 -e MONGODB_PORT=27017 \
               --name backendNode -p 8888:9876 -d livelygig/backend /usr/local/splicious/run.sh**

**Comment by n10n** [comment]
It already was there but added more clarification as you suggested.
