### ISSUE TITLE
Cannot run node based on docker image

### ISSUE THREAD

**Issue by vega113** [synereo/dockernode#7]
I followed the instructions in README, but when running the docker - the node cannot be accessed via URL. 
There are a few errors in the logs provided by docker - attached.
I checked on Mac using docker version 1.12.0

[snode.txt](https://github.com/synereo/dockernode/files/479894/snode.txt)

**Comment by n10n** [comment]
Hello,
This issue is due to changes in Alpine Linux and we are working it. Mean time, please use the pre-built Docker image (one version behind from the current code base) and below is the link:
https://hub.docker.com/r/livelygig/synerodeveloper/ (Use 1.1 tag).

**Comment by n10n** [comment]
Updated the docker image and follow the instruction. Please run it again and report if you encounter any issues.

**Comment by vega113** [comment]
Thanks
Still doesn't work for me. 
I could build and run the image, but when trying to load the https://localhost the browser would display `The requested resource could not be found.`
Here are the logs:
[snode2.txt](https://github.com/synereo/dockernode/files/482881/snode2.txt)

**Comment by vega113** [comment]
I tried the livelygig/synerodeveloper:1.1 - was able to access it on the https://localhost but then got
`apiHostUnreachableError - The Api host you provided is unreachable, Please provide a new one!`

**Comment by n10n** [comment]
Which OS are you running on? You need to find ipadress for your docker? I recall, you said its Mac then it should be localhost with new version of Docker and with older version Docker,it is 192.168.99.100. Try again. From Log files, looks like your Docker is working.

**Comment by vega113** [comment]
It is Mac with docker version 1.12.0.
I tried https://localhost on both images.

**Comment by n10n** [comment]
After looking into output log files, I don't see any issue and server is running fine. I don't have enough information to help diagnose the issue hence let's get into docker and run "netstat -tpnl" command. To get into docker, I'm sure you already know that... docker exec -it <container_name> /bin/bash

**Comment by n10n** [comment]
Continued from prior comments - 9876 port must be open and listening with java process.
Also open your browser's console and then network tab. See if there is an error there and attach the screenshot.

**Comment by n10n** [comment]
vega113 , I just recorded a video and your Docker creation output should be similar to that. https://synereonet.slack.com/files/n/F2DV33V8R/creatingdocker-segment_1.mp4. Can you try to create once more? Just make sure there are no error while creating Docker image. Hopefully this is last time you would need to try.

**Comment by vega113** [comment]
Ok I tried once again from the scratch and it worked.
Thanks
